export const ActionTypes = {
    SET_TV_LOADING: "SET_TV_LOADING",
    SET_MOVIE_LOADING: "SET_MOVIE_LOADING",
    SET_DETAIL_LOADING: "SET_DETAIL_LOADING",
    GET_MOVIES: "GET_MOVIES",
    GET_DETAIL_MOVIE: "GET_DETAIL_MOVIE",
    GET_TV: "GET_TV",
    GET_STORY: "GET_STORY",
}