export const ActionTypes = {
    SET_TV_LOADING: "SET_TV_LOADING",
    SET_MOVIE_LOADING: "SET_MOVIE_LOADING",
    SET_DETAIL_LOADING: "SET_DETAIL_LOADING",
    GET_MOVIES: "GET_MOVIES",
    GET_LOCAL_MOVIES: "GET_LOCAL_MOVIES",
    GET_SIMILAR_MOVIES: "GET_SIMILAR_MOVIES",
    GET_DETAIL_MOVIE: "GET_DETAIL_MOVIE",
    GET_TV: "GET_TV",
    GET_LOCAL_TV: "GET_LOCAL_TV",
    GET_STORY: "GET_STORY",
    GET_LOCAL_STORY: "GET_LOCAL_STORY",
    GET_MOVIE_BOOKMARK: "GET_MOVIE_BOOKMARK",
}